apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.main.type }}
  ports:
    - port: {{ .Values.service.main.port }}
      targetPort: 32400
      protocol: TCP
      name: http
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.tcp.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}-lb-tcp
  labels:
    {{- include "plex.labels" . | nindent 4 }}
  {{- with .Values.service.tcp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.tcp.type }}
  ports:
  {{- range .Values.service.tcp.ports }}
    - name: plex-{{ .port }}
      targetPort: {{ .containerPort }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.udp.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}-lb-udp
  labels:
    {{- include "plex.labels" . | nindent 4 }}
  {{- with .Values.service.udp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.udp.type }}
  ports:
    {{- range .Values.service.udp.ports }}
    - name: plex-{{ .port }}
      targetPort: {{ .containerPort }}
      protocol: UDP
    {{- end }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
{{- end }}
